### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by matthewbauer** [lepisma/org-books#1]
Hi,

This package looks very useful. Would you consider adding it to MELPA?

**Comment by lepisma** [comment]
Sure, but right now its pretty specific to how I use it. After a few fixes #2, #3 it should be fine.

**Comment by Anonyfox** [comment]
I would like to use this, too! Any updates on MELPA releasing? :)

**Comment by olavfosse** [comment]
Just came by to say that there is still interest in adding Melpa support.

**Comment by lepisma** [comment]
made PR here → https://github.com/melpa/melpa/pull/6893

**Comment by lepisma** [comment]
closing now

**Comment by olavfosse** [comment]
Great! Thank you.
