### ISSUE TITLE
`Helm-org' has removed function `helm-org-get-candidates'

### ISSUE THREAD

**Issue by onehr** [lepisma/org-books#13]
First of all, thanks for providing this package, this is what I'm looking for!

One small problem is that we need to install the `helm-org` version 1.0 from MELPA stable. Seems currently they have removed the function `helm-org-get-candidates' from helm-org package.

**Comment by lepisma** [comment]
:cry: [Right](https://github.com/emacs-helm/helm-org/commit/8e875b048a0ac47d0b57951aecb6715220a38e6b). I wish we had version pinning of some sort. Anyway fixing it here.

**Comment by lepisma** [comment]
uh, i didn't even list it in the `Package-Requires` line.
