### ISSUE TITLE
Adding new sources

### ISSUE THREAD

**Issue by Bassmann** [lepisma/org-books#15]
What is the expected way to add new sources? Right now the existing sources seem to be hard-coded in org-books-get-details? I'd like to add Manning since I read a lot of their books in particular in their early access program whihc isn't yet on Amazon.

Thanks for sharing this nice package by the way!

**Comment by lepisma** [comment]
Hi. Thanks for this. I made the process simpler in 0.2.19. Check the doc [here](https://github.com/lepisma/org-books#adding-new-source) and let me know if this works.

Basically now you need to just focus on the variable `org-books-url-pattern-dispatches`.
