### ISSUE TITLE
Support foreign amazon domains

### ISSUE THREAD

**Issue by meliache** [lepisma/org-books#5]
I live in Germany, so I use the `amazon.de`, which is pretty much identical to `amazon.com`, but just for Germany. It would be nice, if `org-books-add-url` also worked with `amazon.de`, `amazon.fr`, and other foreign amazon domains, if it is not too difficult to adapt the metadata getter.

**Comment by lepisma** [comment]
Right, I have also faced this issue. I added an improvement in d47ecc73bcadf2cab2b272c264ab89847e956298, assuming that the webpage structure is the same so metadata thing should work okay.
